query discounts(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  discounts(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      active
      amount
      applyOn
      description
      img
      imgCdn
      name
      q
      ruleType
      type
      maximumUsage
      startDate
      endDate
      numberOfTimeUsed
    }
  }
}
