query categoryAttributes($category: ID!) {
  categoryAttributes(category: $category) {
    count
    page
    pageSize
    data {
      id
      name
      show
      category
      active
      createdAt
      updatedAt
    }
  }
}
