query storeVendorInfo($store: ID!) {
  storeVendorInfo(store: $store) {
    count
    page
    pageSize
    data {
      id
      businessName
      bankAccountNo
      bankName
      bankIfsc
      bankAccountHolderName
      bankSwiftCode
      banner
      bannerCdn
      commissionType
      commissionValue
      createdAt
      updatedAt
      zips
      country {
        id
        name
      }
      user {
        id
      }
      address {
        id
      }
      store {
        id
        name
        email
      }
    }
  }
}
