mutation deleteProductViaBarcode($barcodes: [String!]!, $force: Boolean) {
  deleteProductViaBarcode(barcodes: $barcodes, force: $force)
}

# {
#   "barcodes": [98798798765002,98798798222765003],
#   "force": true
# }
