query invalidVendor(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $category: String
  $store: ID
  $active: Boolean
) {
  invalidVendor(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    category: $category
    store: $store
    active: $active
  ) {
    data {
      id
      slug
      name
      type
      price
      stock
      img
      imgCdn
      images
      time
      vendor {
        id
        firstName
        lastName
        phone
        email
        info {
          store
          storePhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
