query productEs($query: String) {
  productEs(query: $query) {
    took
    count
    data {
      _index
      _type
      _score
      _source {
        sku
        barcode
        name
        slug
        price
        mrp
        img
        imgCdn
        images
        imagesCdn
        brand {
          name
        }
        color {
          name
        }
      }
    }
  }
}
