query productSlug($slug: String!) {
  productSlug(slug: $slug) {
    id
    name
    slug
    img
    imgCdn
    images
    imagesCdn
    price
    stock
    ratings
    reviews
    vendor {
      id
      firstName
      lastName
      city
      avatar
      ratings
      reviews
      info {
        store
        public
        storePhotos
      }
    }
  }
}
