query product1($id: ID!) {
  product1(id: $id) {
    id
    slug
    name
    description
    type
    price
    mrp
    discount
    stock
    tax
    img
    imgCdn
    images
    imagesCdn
    time
    active
    popularity
    position
    sku
    hsn
    group
    barcode
    gender
    gtin
    condition
    itemId
    warranty
    trending
    featured
    hot
    new
    sale
    recommended
    title
    metaDescription
    keywords
    keywordsA
    itemId
    warranty
    ageMin
    ageMax
    ageUnit
    styleCode
    eanNo
    articleCode
    productMasterId
    currency
    manufacturer
    countryOfOrigin
    returnInfo
    link
    gender
    condition
    gtin
    cgst
    sgst
    igst
    keyFeatures
    returnInfo
    brand
    parentBrand
    color {
      color_code
    }
    size
    sizechart
    features
    channels
    category
    categories
    categoryPool
    variants
    options
    vendorInfo
    vendor
    weight
    length
    width
    height
    returnAllowed
    replaceAllowed
    returnValidityInDays
    replaceValidityInDays
    files
    batchNo
    mfgDate
    expiryDate
    unit
    dimensionUnit
    isSearchable
    isUnlimited
    totalSold
    preOrder
    zips
    foodType
    slots
    location
    country
    formattedMrp
    formattedPrice
    deliveryDetails
    productDetails {
      name
      value
    }
    specifications {
      id
      name
      value
    }
    relatedProducts {
      id
      name
      slug
      img
    }
  }
}
