query importDetails(
  $importNo: String
  $type: String
  $success: String
  $page: Int
  $limit: Int
  $search: String
  $where: String
  $sort: String
) {
  importDetails(
    importNo: $importNo
    type: $type
    success: $success
    page: $page
    search: $search
    where: $where
    limit: $limit
    sort: $sort
  ) {
    count
    pageSize
    page
    data {
      id
      importNo
      rawNo
      totalItems
      message
      fileName
      type
      success
      user
    }
  }
}
