query option($id: ID!) {
  option(id: $id) {
    id
    name
    key
    val
    categories
    position
    info
    preselect
    required
    type
    isFilter
    active
    default_option
    store
    values {
      id
      name
      default
      position
      direction
      type
      amount
    }
  }
}
