mutation saveOption(
  $id: String!
  $pid: ID
  $name: String
  $key: String
  $val: String
  $categories: [String]
  $position: Int
  $isFilter: Boolean
  $preselect: Boolean
  $required: Boolean
  $type: String
  $info: String
  $default_option: ID
  $store: ID
  $active: Boolean
) {
  saveOption(
    id: $id
    pid: $pid
    name: $name
    key: $key
    val: $val
    categories: $categories
    position: $position
    isFilter: $isFilter
    info: $info
    preselect: $preselect
    required: $required
    type: $type
    default_option: $default_option
    store: $store
    active: $active
  ) {
    id
    pid
    name
    key
    val
    categories
    position
    info
    preselect
    required
    type
    isFilter
    active
    default_option
    store
    values {
      id
      name
      default
      position
      direction
      type
      amount
    }
  }
}

# {
#   "id": "new",
#   "pid": "60151b263101e96f152d5157",
#   "name": "color2",
#   "type": "text field"
# }
