mutation buySubscription($subscriptionId: ID!) {
  buySubscription(subscriptionId: $subscriptionId) {
    appId
    orderId
    orderAmount
    orderCurrency
    orderNote
    customerName
    customerEmail
    customerPhone
    returnUrl
    notifyUrl
    signature
    token
    url
    stage
  }
}
