query mySubscribes($page: Int, $limit: Int, $search: String, $sort: String) {
  mySubscribes(page: $page, limit: $limit, search: $search, sort: $sort) {
    count
    page
    data {
      id
      amount
      daysLeft
      EndTime
      EndTimeISO
      img
      onGoing
      StartTime
      StartTimeISO
      createdAt
      updatedAt
      subscription {
        id
        active
      }
    }
  }
}
