query subscribes($page: Int, $limit: Int, $search: String, $sort: String) {
  subscribes(page: $page, limit: $limit, search: $search, sort: $sort) {
    count
    page
    data {
      id
      amount
      daysLeft
      EndTime
      EndTimeISO
      img
      onGoing
      StartTime
      StartTimeISO
      createdAt
      updatedAt
      user {
        id
        firstName
      }
      subscription {
        id
        active
      }
      payment {
        id
        amountDue
        amountPaid
        refundStatus
        paymentMode
        paymentGateway
      }
    }
  }
}
