query subscribe($id: ID!) {
  subscribe(id: $id) {
    id
    amount
    daysLeft
    EndTime
    EndTimeISO
    img
    onGoing
    StartTime
    StartTimeISO
    subscription {
      id
      name
    }
    user {
      id
      firstName
    }
    createdAt
    updatedAt
    payment {
      id
      amountDue
      amountPaid
      refundStatus
      paymentMode
      paymentGateway
    }
  }
}
