query coupons(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  coupons(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      code
      value
      type
      info
      msg
      text
      terms
      color
      minimumCartValue
      maxAmount
      usesPerCustomer
      validFromDate
      validToDate
      active
      createdAt
      updatedAt
    }
  }
}
