query profile($id: ID!) {
  profile(id: $id) {
    id
    email
    firstName
    lastName
    avatar
    avatarCdn
    banner
    address
    city
    state
    zip
    phone
    active
    type
    carbon_neutral
    badges
    subscription_from
    subscription_to
  }
}
