mutation register(
  $email: String!
  $password: String!
  $passwordConfirmation: String!
  $firstName: String
  $lastName: String
  $referrer: String
  $role: String
  $phone: String
  $store: ID
) {
  register(
    email: $email
    password: $password
    passwordConfirmation: $passwordConfirmation
    firstName: $firstName
    lastName: $lastName
    referrer: $referrer
    role: $role
    phone: $phone
    store: $store
  ) {
    id
    email
    firstName
    lastName
    city
    phone
    role
    verified
    active
    avatar
    avatarCdn
    provider
    createdAt
    updatedAt
  }
}
