mutation resetPassword(
  $id: ID!
  $token: String!
  $password: String!
  $passwordConfirmation: String
) {
  resetPassword(
    id: $id
    token: $token
    password: $password
    passwordConfirmation: $passwordConfirmation
  )
}
