query stores {
  stores {
    id
    email
    firstName
    lastName
    address
    town
    city
    country
    state
    zip
    phone
    active
    createdAt
    updatedAt
  }
}
