mutation signInWithApple($code: String!) {
  signInWithApple(code: $code) {
    id
    email
    firstName
    lastName
    city
    phone
    avatar
    avatarCdn
    role
    verified
    active
    provider
    createdAt
    updatedAt
  }
}
