query users(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $role: String
  $store: ID
) {
  users(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    role: $role
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      email
      firstName
      lastName
      name
      avatar
      avatarCdn
      city
      phone
      role
      verified
      active
      productSold
      luluCustomerNo
      plan
      createdAt
      updatedAt
      address {
        address
        city
      }
      info {
        store
        public
      }
      store {
        name
      }
    }
  }
}
