query myTransactions(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $q: String
) {
  myTransactions(
    page: $page
    skip: $skip
    search: $search
    limit: $limit
    sort: $sort
    q: $q
  ) {
    count
    page
    pageSize
    data {
      id
      amount
      remark
      direction
      user
      balance
      referedUser
      createdAt
      updatedAt
    }
  }
}
