mutation saveReview(
  $id: String!
  $pid: ID
  $variant: ID
  $user: ID
  $rating: Int
  $message: String
  $active: Boolean
  $store: ID
) {
  saveReview(
    id: $id
    pid: $pid
    variant: $variant
    user: $user
    rating: $rating
    message: $message
    active: $active
    store: $store
  ) {
    id
    pid
    user
    store
    rating
    message
    active
  }
}
