<template>
  <section class="bg-white min-h-screen">
    <Megamenu class="hidden lg:flex px-10" />

    <div
      class="
        container
        max-w-7xl
        mx-auto
        px-4
        md:px-10
        lg:px-16
        text-gray-800 text-center
      "
    >
      <h1
        class="
          text-2xl
          md:text-4xl
          tracking-wide
          text-center
          pt-10
          pb-5
          text-gray-500
        "
      >
        Promotion Terms & Conditions
      </h1>

      <ul class="space-y-5">
        <li v-for="(i, ix) in items" :key="ix" class="flex flex-col text-sm">
          <h4 class="mb-5 font-medium text-lg md:text-2xl">{{ i.heading }}</h4>

          <p class="text-sm mb-5">{{ i.data }}</p>
        </li>
      </ul>
    </div>

    <WantMore class="mt-5 md:mt-10" />
    <!-- <WhiteFooter class="mt-10 md:mt-20" /> -->
  </section>
</template>

<script>
import Megamenu from '~/components/Home/Megamenu.vue'
import WantMore from '~/components/Island/WantMore.vue'
import WhiteFooter from '~/components/Island/WhiteFooter.vue'

export default {
  components: { Megamenu, WantMore, WhiteFooter },

  data() {
    return {
      items: [
        {
          heading: 'Free standard delivery',

          data: `*Free standard UK delivery only available on orders valued over £50. Discount automatically applied at checkout. Offer only available on riverisland.com for a limited time and excludes gift cards.`,
        },
        {
          heading: 'Free Click & Collect',

          data: `Free Click & Collect delivered to your local River Island store available on orders valued over £20 and when you select the deliver to local store icon at checkout. Otherwise £1. Offer only available on riverisland.com. Excludes gift card purchases.`,
        },
        {
          heading: 'Exclusive customer promo',

          data: `*15% off full-price products when you spend £/€40.00 or more on our website at www.riverisland.com / www.riverisland.com/ie or at our stores in the UK & Ireland. Offer valid online on River Island’s website at www.riverisland.com / www.riverisland.com/ie and in River Island’s stores in the UK & Ireland. Offer must be redeemed between 00.00 AM on 9th July 2021 and 11.59 PM on 31st July 2021. Eligible customers are provided with a unique discount code via email which will apply to eligible products. Eligible customers must use their unique discount code provided on their online basket before check-out stage or must show it to a River Island member of staff in-store before payment is processed. Any refunds of full-price products will be processed after the value of the discount is applied. The minimum spend is £/€40.00. The unique discount code can only be used once and it is not transferable.`,
        },
        {
          heading: 'Seasonal Offers',

          data: `*Up to 30% off womenswear, menswear and kidswear, online and in-store. Selected lines only. Offer cannot be used in conjunction with any other promotions. Returned items will be refunded at the discounted price paid on production of a valid receipt. Discount does not apply to website delivery charges.`,
        },
        {
          heading:
            '2 for £45 / 3 for £65 on selected men’s sweatshirts and joggers',

          data: `*2 for £45 / 3 for £65 on selected men’s sweatshirts and joggers. Offer only available online from 00:00 BST 4th August 2019. Returned items will be refunded at the discounted price paid on production of a valid receipt. Offer cannot be used in conjunction with any other promotions or sale items. Discount does not apply to website delivery charges and will be automatically applied at checkout.`,
        },
        {
          heading: 'Competitions',

          data: `All competition terms and conditions can be read here.`,
        },
        {
          heading: 'Student discount',

          data: `*Students! Get up to 10% off with Student Beans & UNiDAYS The 10% student discount is available online from 00:00 26th April 2021 until 23:59 31th December 2021 to customers who have signed up through Student Beans or UNiDAYS online or to those with a student ID with a valid photo and date in participating River Island stores in England, Scotland and Wales. Customers of this promotion must sign up for email receipts and marketing to redeem this offer. The discount offers 10% off full-priced menswear, womenswear & kidswear, excluding delivery and gift cards. Returned items will be refunded at the discounted price, paid on production of valid receipt. This offer cannot be used in conjunction with any other offer and excludes brands. Student discount should be redeemed online by entering the unique code generated by Student Beans or UNiDAYS into the promotion code box in the shopping bag at check out. Student Beans & UNiDAYS discounts are only available on www.riverisland.com and www.riverisland.ie It is unfortunately not available on the iPad or iPhone apps at this time. You can however redeem the discount on orders placed via the mobile browsers on these devices.`,
        },
        {
          heading: 'Get 15% off with Blue Light Card',

          data: `*The 15% discount is only available from 00:00 1st March 2021 until 23:59 25th December 2021 in participating River Island stores in the UK and Republic of Ireland (excluding Voisins, Jersey & Isle of Man’) and online for customers who have signed up through Blue Light Card. The Blue Light Card discount offers 15% off full-priced items, excluding delivery. Blue Light Card discount should be redeemed by entering the unique code generated by Blue Light Card into the regular discount box in the online shopping bag or by presenting the Blue Light Card to store staff at the checkout point. Customers of this promotion must sign up for email receipts and marketing to redeem this offer in store. The online Blue Light Card discount is only available on www.riverisland.com/www.riverisland.ie . It is unfortunately not available on the iPad or iPhone apps at this time. You can however redeem the discount on orders placed via the mobile browsers on these devices. One voucher per transaction. Offer excludes delivery charges and gift cards. Returned items will be refunded at the discounted price, paid on production of valid receipt. This offer cannot be used in conjunction with any other offer, sale items or gift cards. See your nearest store for further details. Offer excludes brands.`,
        },
      ],
    }
  },

  head() {
    return {
      title: 'Promotion Terms & Conditions',
    }
  },
}
</script>

<style scoped></style>
