mutation fileUploadFromUrl($url: String!, $folder: String!) {
  fileUploadFromUrl(url: $url, folder: $folder) {
    mimetype
    filename
    url
  }
}

#  {
#   "url": "https://cdn.pixabay.com/photo/2015/03/26/09/41/chain-690088_1280.jpg",
#   "folder": "category"
# }
