mutation fileUpload($files: [Upload!], $folder: String, $productId: ID) {
  fileUpload(files: $files, folder: $folder, productId: $productId) {
    filename
    mimetype
    encoding
    url
  }
}
