mutation updateShippoData($orderItemId: ID!) {
  updateShippoData(orderItemId: $orderItemId) {
    id
    orderId
    status
    pid
    posInvoiceNo
    invoiceId
    itemOrderNo
    name
    slug
    img
    imgCdn
    tracking
    shippingCharge
    price
    basePrice
    qty
    tax
    baseTax
    total
    totalDiscount
    subtotal
    brandName
    brandImg
    brandImgCdn
    size
    color
    trackingId
    returnTrackingId
    courierName
    returnCourierName
    type
    amountRefunded
    baseAmountRefunded
    refunds {
      message
      qty
      time
      amount
      refundId
    }
    shippingOrderId
    shippingProvider
    shippingLabelId
    shippingRateId
    shippingTrackingNumber
    shippingTrackingStatus
    shippingTrackingUrlProvider
    shippingLabelUrl
    shippingCommercialInvoiceUrl
    #order level info
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    invoiceId
    paymentGateway
    codPaid
    baseCodPaid
    amountPaid
    amountDue
    totalAmountRefunded
    baseTotalAmountRefunded
    paymentMsg
    paymentTime
    paid
    userFirstName
    userLastName
    userPhone
    userEmail
    invoiceLink
    returnValidTill
    returnReason
    discount
    baseDiscount
    totalDiscount
    baseTotalDiscount
    vendorCommission
    amount {
      total
      discount
      totalDiscount
      subtotal
    }
    baseAmount {
      total
      discount
      totalDiscount
      subtotal
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    slot {
      name
      value
      info
      active
    }
    vendorAddress {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    orderHistory {
      id
      status
      title
      body
      icon
      public
      index
      time
    }
  }
}
