query gdprDataDeleteRequests(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
) {
  gdprDataDeleteRequests(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
  ) {
    count
    page
    pageSize
    data {
      id
      comment
      description
      email
      reason
      status
      createdAt
      user {
        id
        firstName
        lastName
        email
        phone
      }
    }
  }
}
