mutation gdprDataDeleteRequest($reason: String, $description: String) {
  gdprDataDeleteRequest(reason: $reason, description: $description) {
    id
    reason
    description
    email
    comment
    status
    user
  }
}
