query summary {
  userSummary {
    count
  }
  productSummary {
    count
  }
  categorySummary {
    count
  }
  orderSummary {
    count
    amount
  }
  paymentsSummary {
    count
    amount
  }
}
