query page($id: String) {
  page(id: $id) {
    id
    name
    slug
    title
    metaDescription
    keywords
    content
    menuTitle
    active
    createdAt
    updatedAt
    user {
      name
    }
    store {
      id
      name
    }
  }
}
