query faqs(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  faqs(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      question
      topic
      answer
      active
      opened
      createdAt
      updatedAt
      store {
        id
        name
        email
      }
    }
  }
}
