mutation saveFaqTopic(
  $id: String!
  $name: String
  $for: String
  $active: Boolean
) {
  saveFaqTopic(id: $id, name: $name, for: $for, active: $active) {
    id
    name
    for
    uid
    active
    createdAt
    updatedAt
  }
}
