query channels(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $user: ID
  $q: String
  $upcoming: Boolean
) {
  channels(
    page: $page
    skip: $skip
    search: $search
    limit: $limit
    sort: $sort
    user: $user
    q: $q
    upcoming: $upcoming
  ) {
    count
    page
    pageSize
    data {
      id
      scheduleDateTime
      title
      img
      imgCdn
      isLive
      requestId
      cid
      ctime
      pushUrl
      httpPullUrl
      hlsPullUrl
      rtmpPullUrl
      name
      code
      msg
      product {
        id
        name
        img
        slug
        price
        mrp
      }
      products {
        id
        name
        img
        slug
        price
        mrp
      }
      user {
        id
        firstName
        lastName
        email
        phone
        avatar
        avatarCdn
      }
      users {
        id
        firstName
        lastName
        email
        phone
      }
    }
  }
}
