mutation saveSettings(
  $id: ID!
  $websiteName: String
  $websiteLegalName: String
  $closed: Boolean
  $liveCommerce: Boolean
  $closedMessage: String
  $otpLogin: Boolean
  $demo: Boolean
  $minimumOrderValue: Int
  $title: String
  $alert: String
  $keywords: String
  $description: String
  $currency: ID
  $currencyCode: String
  $currencySymbol: String
  $currencyDecimals: Int
  $openGraphImage: String
  $tax: TaxIp
  $shipping: ShippingIp
  $websiteEmail: String
  $shopPhone: String
  $shopAddress: String
  $country: ID
  $logo: String
  $logoMobile: String
  $logoDark: String
  $logoMobileDark: String
  $favicon: String
  $CDN_URL: String
  $searchbarText: String
  $pageSize: Int
  $paymentStatuses: [String]
  $sms: SmsIp
  $email: EmailIp
  $storage: StorageIp
  $storageProvider: String
  $review: ReviewSettingIp
  $product: ProductSettingIp
  $login: LoginSettingIp
  $googleMapsApi: String
  $facebook: String
  $twitter: String
  $google: String
  $instagram: String
  $linkedin: String
  $enableTax: Boolean
  $stripePublishableKey: String
  $brainTreePublicKey: String
  $enableStripe: Boolean
  $enableRazorpay: Boolean
  $RAZORPAY_KEY_ID: String
  $locationExpiry: Float
  $multilingual: Boolean
  $customerOrderNotifications: UserNotificationIp
  $adminNotifications: AdminNotificationIp
  $referralBonus: Float
  $joiningBonus: Float
  $isMultiVendor: Boolean
  $isMultiStore: Boolean
  $isMegamenu: Boolean
  $isVerifyEmail: Boolean
  $isSearch: Boolean
  $isSaas: Boolean
) {
  saveSettings(
    id: $id
    websiteName: $websiteName
    websiteLegalName: $websiteLegalName
    liveCommerce: $liveCommerce
    multilingual: $multilingual
    closed: $closed
    closedMessage: $closedMessage
    otpLogin: $otpLogin
    demo: $demo
    minimumOrderValue: $minimumOrderValue
    title: $title
    alert: $alert
    keywords: $keywords
    description: $description
    currency: $currency
    currencyCode: $currencyCode
    currencySymbol: $currencySymbol
    currencyDecimals: $currencyDecimals
    openGraphImage: $openGraphImage
    tax: $tax
    shipping: $shipping
    websiteEmail: $websiteEmail
    shopPhone: $shopPhone
    shopAddress: $shopAddress
    country: $country
    logo: $logo
    logoMobile: $logoMobile
    logoDark: $logoDark
    logoMobileDark: $logoMobileDark
    favicon: $favicon
    CDN_URL: $CDN_URL
    searchbarText: $searchbarText
    pageSize: $pageSize
    paymentStatuses: $paymentStatuses
    sms: $sms
    email: $email
    storage: $storage
    storageProvider: $storageProvider
    review: $review
    product: $product
    login: $login
    googleMapsApi: $googleMapsApi
    facebook: $facebook
    twitter: $twitter
    google: $google
    instagram: $instagram
    linkedin: $linkedin
    enableTax: $enableTax
    RAZORPAY_KEY_ID: $RAZORPAY_KEY_ID
    stripePublishableKey: $stripePublishableKey
    brainTreePublicKey: $brainTreePublicKey
    enableStripe: $enableStripe
    enableRazorpay: $enableRazorpay
    locationExpiry: $locationExpiry
    customerOrderNotifications: $customerOrderNotifications
    adminNotifications: $adminNotifications
    referralBonus: $referralBonus
    joiningBonus: $joiningBonus
    isMultiVendor: $isMultiVendor
    isMultiStore: $isMultiStore
    isMegamenu: $isMegamenu
    isVerifyEmail: $isVerifyEmail
    isSearch: $isSearch
    isSaas: $isSaas
  ) {
    websiteName
    websiteLegalName
    liveCommerce
    multilingual
    closed
    closedMessage
    otpLogin
    demo
    title
    alert
    keywords
    description
    currency
    currencyCode
    currencySymbol
    tax {
      cgst
      sgst
      igst
    }
    shipping {
      deliveryDays
      charge
      free
      method
      enabled
      provider
    }
    websiteEmail
    shopPhone
    shopAddress
    country
    logo
    logoMobile
    logoDark
    logoMobileDark
    favicon
    CDN_URL
    searchbarText
    pageSize
    orderStatuses {
      status
      title
      body
      icon
    }
    paymentStatuses
    sms {
      AUTO_VERIFICATION_ID
      enabled
      provider
    }
    email {
      enabled
      from
      to
      cc
      bcc
      printers
    }
    storage {
      enabled
      provider
    }
    storageProvider
    review {
      moderate
      enabled
    }
    product {
      moderate
    }
    login {
      FACEBOOK_ID
      FACEBOOK_SECRET
      TWITTER_ID
      TWITTER_SECRET
      GOOGLE_ID
      GOOGLE_SECRET
      GITHUB_ID
      GITHUB_SECRET
    }
    customerOrderNotifications {
      orderConfirmation
      orderStatusChanged
      orderShipped
      orderIsReadyForPickup
      downloadEGoods
      giftCardPurchased
    }
    adminNotifications {
      newOrderPlaced
      lowStockNotification
    }
    googleMapsApi
    facebook
    twitter
    google
    instagram
    linkedin
    RAZORPAY_KEY_ID
    stripePublishableKey
    brainTreePublicKey
    locationExpiry
    joiningBonus
    referralBonus
    isMultiVendor
    isMultiStore
    isMegamenu
    isVerifyEmail
    isSearch
  }
}
