subscription {
  settingsUpdated {
    id
    websiteName
    closed
    closedMessage
    minimumOrderValue
    title
    alert
    keywords
    description
    tax {
      cgst
      sgst
      igst
    }
    RAZORPAY_KEY_ID
    stripePublishableKey
    brainTreePublicKey
    enableStripe
    enableRazorpay
    currencyCode
    currencySymbol
    currencyDecimals
    openGraphImage
    shipping {
      deliveryDays
      charge
      free
      method
    }
    userRoles
    websiteEmail
    shopPhone
    shopAddress
    logo
    logoMobile
    logoDark
    logoMobileDark
    favicon
    CDN_URL
    searchbarText
    pageSize
    orderStatuses {
      status
      title
      body
      icon
    }
    paymentStatuses
    sms {
      enabled
      provider
    }
    email {
      enabled
      from
      cc
      bcc
      printers
    }
    storage {
      enabled
      provider
    }
    review {
      enabled
      moderate
    }
    product {
      moderate
    }
    login {
      FACEBOOK_ID
      FACEBOOK_SECRET
      TWITTER_ID
      TWITTER_SECRET
      GOOGLE_ID
      GOOGLE_SECRET
      GITHUB_ID
      GITHUB_SECRET
    }
    customerOrderNotifications {
      orderConfirmation
      orderStatusChanged
      orderShipped
      orderIsReadyForPickup
      downloadEGoods
      giftCardPurchased
    }
    adminNotifications {
      newOrderPlaced
      lowStockNotification
    }
    googleMapsApi
    facebook
    twitter
    google
    instagram
    enableTax
    locationExpiry
    referralBonus
    joiningBonus
  }
}
