query collectionsProducts($ids: [ID!]) {
  collectionsProducts(ids: $ids) {
    count
    pageSize
    noOfPage
    page
    data {
      id
      name
      description
      slug
      type
      city
      price
      mrp
      stock
      tax
      img
      imgCdn
      images
      time
      active
      popularity
      sku
      hsn
      group
      barcode
      position
      trending
      featured
      hot
      new
      sale
      recommended
      title
      metaDescription
      keywords
      itemId
      warranty
      ageMin
      ageMax
      ageUnit
      styleCode
      styleId
      eanNo
      articleCode
      productMasterId
      currency
      manufacturer
      countryOfOrigin
      returnInfo
      gender
      condition
      gtin
      cgst
      sgst
      igst
    }
  }
}
