query cart($store: ID) {
  cart(store: $store) {
    id
    currency
    currencyCode
    currencyName
    currencySymbol
    items {
      pid
      barcode
      tax
      name
      slug
      qty
      price
      mrp
      shippingCharge
      img
      imgCdn
      options
      tracking
      brandName
      vendorInfoBusinessName
      foodType
      vendor {
        id
        firstName
        email
      }
      formattedItemAmount {
        mrp
        price
        tax
        shippingCharge
      }
    }
    qty
    tax
    subtotal
    total
    discount {
      code
      value
      text
      amount
    }
    shipping {
      charge
    }
    formattedAmount {
      offer_total
      tax
      subtotal
      total
    }
  }
}
