mutation saveOptionValue(
  $id: String!
  $option_id: ID
  $name: String
  $default: Boolean
  $position: Int
  $amount: Float
  $type: String
  $direction: String
  $active: Boolean
) {
  saveOptionValue(
    id: $id
    option_id: $option_id
    name: $name
    default: $default
    position: $position
    amount: $amount
    type: $type
    direction: $direction
    active: $active
  ) {
    id
    option_id
    name
    default
    position
    direction
    type
    amount
    active
  }
}

# {
#    "id": "new",
#   "option_id": "60557db71d76790db44dd096",
#    "name": "green",
#   "default": true
#  }
