mutation savePopularSearch(
  $id: String!
  $text: String
  $popularity: String
  $store: ID
) {
  savePopularSearch(
    id: $id
    text: $text
    popularity: $popularity
    store: $store
  ) {
    id
    text
    popularity
    store
  }
}

# {
#   "id": "new",
#   "text": "prak",
#   "popularity": "pra@",
#   "store": "61004670de02af2608738e9a"
# }
