query banner($id: String!) {
  banner(id: $id) {
    id
    link
    heading
    img
    imgCdn
    type
    sort
    store
    groupId
    groupTitle
    pageId
    active
    isMobile
    createdAt
    updatedAt
  }
}
