query allCategories(
  $page: Int
  $search: String
  $limit: Int
  $level: Int
  $sort: String
  $megamenu: Boolean
  $featured: Boolean
  $active: Boolean
  $shopbycategory: Boolean
  $store: ID
) {
  allCategories(
    page: $page
    search: $search
    limit: $limit
    level: $level
    sort: $sort
    megamenu: $megamenu
    featured: $featured
    active: $active
    shopbycategory: $shopbycategory
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      namePath
      level
      categoryId
    }
  }
}
