query megamenuAll($id: ID, $search: String, $sort: String, $featured: Boolean) {
  megamenuAll(id: $id, search: $search, sort: $sort, featured: $featured) {
    id
    name
    description
    slug
    img
    imgCdn
    featured
    featuredSort
    categoryId
    position
    parent
    meta
    metaTitle
    metaDescription
    metaKeywords
    keywords
    active
    megamenu
    shopbycategory
    children {
      id
      name
      description
      slug
      img
      featured
      featuredSort
      categoryId
      position
      parent
      meta
      metaTitle
      metaDescription
      metaKeywords
      active
      megamenu
      shopbycategory
      children {
        id
        name
        description
        slug
        img
        featured
        featuredSort
        categoryId
        position
        parent
        meta
        metaTitle
        metaDescription
        metaKeywords
        active
        megamenu
        shopbycategory
        children {
          id
          name
          description
          slug
          img
          featured
          featuredSort
          categoryId
          position
          parent
          meta
          metaTitle
          metaDescription
          metaKeywords
          active
          megamenu
          shopbycategory
          children {
            id
            name
            description
            slug
            img
            featured
            featuredSort
            categoryId
            position
            parent
            meta
            metaTitle
            metaDescription
            metaKeywords
            active
            megamenu
            shopbycategory
            children {
              id
              name
              description
              slug
              img
              featured
              featuredSort
              categoryId
              position
              parent
              meta
              metaTitle
              metaDescription
              metaKeywords
              active
              megamenu
              shopbycategory
            }
          }
        }
      }
    }
  }
}
