query brands(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $parent: String
  $featured: Boolean
  $store: ID
) {
  brands(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    parent: $parent
    featured: $featured
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      brandId
      name
      slug
      img
      imgCdn
      position
      info
      meta
      metaTitle
      metaDescription
      metaKeywords
      facebookUrl
      instaUrl
      twitterUrl
      linkedinUrl
      youtubeUrl
      pinterestUrl
      googleUrl
      banner
      bannerCdn
      active
      featured
      parent {
        id
        name
      }
      store {
        id
        name
        email
        phone
        active
      }
      createdAt
      updatedAt
    }
  }
}
