#new changes
query parentBrands(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $featured: Boolean
) {
  parentBrands(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    featured: $featured
  ) {
    count
    page
    pageSize
    data {
      id
      brandId
      name
      slug
      img
      imgCdn
      position
      meta
      metaTitle
      metaDescription
      metaKeywords
      facebookUrl
      instaUrl
      twitterUrl
      linkedinUrl
      youtubeUrl
      banner
      bannerCdn
      active
      featured
      parent {
        id
      }
      createdAt
      updatedAt
    }
  }
}
