mutation saveBrand(
  $id: String!
  $brandId: String
  $name: String
  $slug: String
  $parent: ID
  $img: String
  $position: Int
  $featured: Boolean
  $info: String
  $meta: String
  $metaTitle: String
  $metaDescription: String
  $metaKeywords: String
  $facebookUrl: String
  $twitterUrl: String
  $linkedinUrl: String
  $youtubeUrl: String
  $instaUrl: String
  $pinterestUrl: String
  $googleUrl: String
  $banner: String
  $active: Boolean
  $store: ID
) {
  saveBrand(
    id: $id
    brandId: $brandId
    name: $name
    slug: $slug
    parent: $parent
    img: $img
    position: $position
    meta: $meta
    info: $info
    metaTitle: $metaTitle
    metaDescription: $metaDescription
    metaKeywords: $metaKeywords
    facebookUrl: $facebookUrl
    twitterUrl: $twitterUrl
    linkedinUrl: $linkedinUrl
    youtubeUrl: $youtubeUrl
    instaUrl: $instaUrl
    pinterestUrl: $pinterestUrl
    googleUrl: $googleUrl
    banner: $banner
    featured: $featured
    active: $active
    store: $store
  ) {
    id
    brandId
    name
    slug
    img
    imgCdn
    info
    meta
    metaTitle
    metaDescription
    metaKeywords
    facebookUrl
    instaUrl
    twitterUrl
    linkedinUrl
    youtubeUrl
    pinterestUrl
    googleUrl
    banner
    bannerCdn
    featured
    active
    store
    createdAt
    updatedAt
  }
}
