query variants($page: Int, $search: String, $limit: Int, $sort: String) {
  variants(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      sku
      images
      sort
      active
      price
      mrp
      weight
      trackInventory
      stock
      unit
      barcode
      options {
        name
      }
      createdAt
      updatedAt
    }
  }
}
