query video($id: String, $slug: String) {
  video(id: $id, slug: $slug) {
    id
    comment
    category
    img
    sort
    featured
    user {
      id
      firstName
      lastName
      avatar
    }
    active
    views
    vid
    taskId
    eventType
    cid
    code
    pieceIndex
    type
    url
    uid
    filename
    size
    channelName
    mix
    channelId
    md5
    timestamp
    substream
    reason
    streamUrl
    createTime
    origUrl
    playSupport
    downloadOrigUrl
    videoName
    durationMsec
    status
    updateTime
    typeName
    duration
    snapshotUrl
    initialSize
    typeId
    shdMp4Url
    sdMp4Size
    downloadSdMp4Url
    description
    hdMp4Size
    downloadSdFlvUrl
    shdMp4Size
    sdFlvUrl
    sdFlvSize
    hdMp4Url
    sdMp4Url
    downloadHdMp4Url
    downloadShdMp4Url
    completeTime
    createdAt
    updatedAt
  }
}
