query myTokens($page: Int, $search: String, $limit: Int, $sort: String) {
  myTokens(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      token
      platform
      device_id
      user_type
      sId
      user {
        id
      }
      active
      createdAt
      updatedAt
    }
  }
}
