query currencies($page: Int, $search: String, $limit: Int, $sort: String) {
  currencies(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      sort
      isoCode
      isoNumericCode
      thousandsSeparator
      decimalMark
      symbolFirst
      active
      symbol
      disambiguateSymbol
      htmlEntity
      subUnit
      smallestDenomination
      subunitToUnit
      createdAt
      updatedAt
    }
  }
}
