query allScheduleDemos(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $q: String
) {
  allScheduleDemos(
    page: $page
    skip: $skip
    search: $search
    limit: $limit
    sort: $sort
    q: $q
  ) {
    count
    page
    pageSize
    data {
      id
      scheduleDateTime
      title
      img
      imgCdn
      product {
        id
        name
        img
        imgCdn
        slug
        price
        mrp
      }
      products {
        id
        name
        img
        imgCdn
        slug
        price
        mrp
      }
      user {
        id
        firstName
        lastName
        email
        phone
      }
      users {
        id
        firstName
        lastName
        email
        phone
      }
    }
  }
}
