query scheduleDemo($id: ID!) {
  scheduleDemo(id: $id) {
    id
    scheduleDateTime
    title
    img
    imgCdn
    product {
      id
      name
      img
      imgCdn
      slug
      price
      mrp
    }
    products {
      id
      name
      img
      slug
      price
      mrp
    }
    user {
      id
      firstName
      lastName
      email
      phone
    }
    users {
      id
      firstName
      lastName
      email
      phone
    }
  }
}
