deployment:
  name: tblz-frontend-deploy
  namespace: tablez-prod
  labels:
    app: tblz-frontend-deploy
  selectorLabels:
    app: tblz-frontend-pod
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  containers:
  - name: tblz-frontend-app
    image: tblzprdacr.azurecr.io/tablez-frontend:latest
    imagePullPolicy: Always
    memoryRequest: "1024Mi"
    cpuRequest: "1000m"
    memoryLimit: "2048Mi"
    cpuLimit: "2000m"
    containerPorts: [4400]
    nodeSelector:
      agentpool: prdapipool
    env:
    - name: WWW_URL
      value: https://pre.tablez.com
    - name: HTTP_ENDPOINT
      value: http://tblz-bkend-service.tablez-prod.svc
    - name: PORT
      value: "4400"
    envFrom:
    - tblz-frontend-analytics-secret
service:
  name: tblz-frontend-service
  namespace: tablez-prod
  selector:
    app: tblz-frontend-pod
  type: ClusterIP
  protocols: [TCP]
  ports: [80]
  targetPorts: [4400]
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  averageCpuUtilization: 60