query locations($page: Int, $search: String, $limit: Int, $sort: String) {
  locations(page: $page, search: $search, limit: $limit, sort: $sort) {
    data {
      id
      name
      active
      lat
      lng
      zips
    }
    count
    pageSize
    page
  }
}
