mutation create($id: ID!, $pid: ID!, $status: String, $tracking: String) {
  create(id: $id, pid: $pid, status: $status, tracking: $tracking) {
    id
    orderNo
    user {
      firstName
      lastName
      phone
    }
    amount {
      qty
      subtotal
      discount
      shipping
      tax
      total
    }
    paymentOrderId
    delivery {
      otp
    }
    items {
      pid
      name
      slug
      img
      price
      qty
      status
      tracking
      vendor {
        firstName
        lastName
        store {
          name
        }
        phone
      }
    }
    address {
      address
      firstName
      lastName
      phone
    }
    createdAt
    updatedAt
  }
}
