mutation createOrder($address: ID, $user: ID!, $items: [ItemIp!]) {
  createOrder(address: $address, user: $user, items: $items) {
    id
    orderNo
    otp
    amount {
      qty
      subtotal
      discount
      shipping
      total
      tax
    }
    paymentOrderId
    paymentMode
    paymentAmount
    paymentCurrency
    paymentReferenceId
    delivery {
      otp
    }
    items {
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      imgCdn
      tracking
      shippingCharge
      tax
      vendor {
        id
        firstName
        lastName
        phone
      }
      brandName
      brandImg
      brandImgCdn
      parentBrandName
      parentBrandImg
      parentBrandImgCdn
    }
    orderItems {
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      tracking
      shippingCharge
      tax
      brandName
      brandImg
      parentBrandName
      parentBrandImg
    }
    address {
      firstName
      lastName
      phone
      lat
      lng
    }
    user {
      id
      firstName
      lastName
      phone
    }
    createdAt
    updatedAt
  }
}

# {
#   "user": "606c127255c00f147499139f",
#   "address": "608ab6af97116f3a88f700d6",
#   "items": [{"id": "60c0d7e9287e0c1e0cccb4c6","qty": 1 }]
# }
