query orders(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  orders(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      imgCdn
      tracking
      shippingCharge
      price
      qty
      tax
      brandName
      brandImg
      brandImgCdn
      size
      color
      trackingId
      returnTrackingId
      courierName
      returnCourierName
      #order level info
      orderNo
      otp
      createdAt
      paySuccess
      paymentMode
      paymentStatus
      paymentCurrency
      paymentReferenceId
      paymentOrderId
      paymentReceipt
      invoiceId
      paymentGateway
      codPaid
      amountPaid
      amountDue
      paymentMsg
      paymentTime
      paid
      userFirstName
      userLastName
      userPhone
      invoiceLink
      returnValidTill
      paymentMode
      paymentAmount
      returnReason
      user {
        firstName
        lastName
        email
        phone
        role
      }
      address {
        firstName
        lastName
        address
        lat
        lng
      }
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      payment {
        amountPaid
        amountDue
      }
      store {
        id
        name
        email
      }
      orderHistory {
        id
        status
        title
        body
        icon
        public
        index
        time
      }
    }
  }
}
