# item status
query ordersByStatus(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $status: String!
) {
  ordersByStatus(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    status: $status
  ) {
    count
    pageSize
    page
    data {
      _id {
        id
        orderNo
        createdAt
        reviewed
        createdAt
        updatedAt
        user {
          firstName
          lastName
          phone
          email
          gender
          info {
            public
            store
            storePhotos
          }
          avatar
        }
        address {
          address
          email
          phone
          firstName
          lastName
        }
        amount {
          qty
          subtotal
          total
          shipping
          discount
        }
        paymentOrderId
      }
      items {
        pid
        name
        slug
        img
        imgCdn
        price
        qty
        time
        status
        vendor {
          store
          firstName
          lastName
          phone
        }
      }
    }
  }
}
