mutation returnOrReplace(
  $orderItemId: ID!
  $reason: String!
  $requestType: String!
) {
  returnOrReplace(
    orderItemId: $orderItemId
    reason: $reason
    requestType: $requestType
  ) {
    id
    orderId
    status
    pid
    posInvoiceNo
    invoiceId
    itemOrderNo
    deliveryDetails
    shippingOrderId
    shippingProvider
    shippingLabelId
    shippingRateId
    shippingTrackingNumber
    shippingTrackingStatus
    shippingTrackingUrlProvider
    shippingLabelUrl
    shippingCommercialInvoiceUrl
    name
    slug
    img
    imgCdn
    tracking
    shippingCharge
    price
    basePrice
    qty
    tax
    baseTax
    total
    totalDiscount
    subtotal
    brandName
    brandImg
    brandImgCdn
    size
    color
    trackingId
    returnTrackingId
    courierName
    returnCourierName
    type
    amountRefunded
    baseAmountRefunded
    refunds {
      message
      qty
      time
      amount
      refundId
    }
    #order level info
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    invoiceId
    paymentGateway
    codPaid
    baseCodPaid
    amountPaid
    amountDue
    totalAmountRefunded
    baseTotalAmountRefunded
    paymentMsg
    paymentTime
    paid
    userFirstName
    userLastName
    userPhone
    userEmail
    invoiceLink
    replaceValidTill
    returnValidTill
    returnReason
    discount
    baseDiscount
    totalDiscount
    baseTotalDiscount
    vendorCommission
    weight
    unit
    amount {
      total
      discount
      totalDiscount
      subtotal
    }
    baseAmount {
      total
      discount
      totalDiscount
      subtotal
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    vendorFirstName
    vendorLastName
    vendorPhone
    vendorEmail
    vendorInfoBusinessName
    vendorInfoCommissionType
    vendorInfoCommissionValue
    vendorAddress {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    formattedSubtotal
    formattedShippingCharge
    formattedMrp
    formattedAmountRefunded
    formattedPrice
    formattedTax
    formattedTotal
    formattedTotalDiscount
    formattedVendorCommission
    formattedAmountDue
    formattedAmountPaid
    formattedCodPaid
    formattedDiscount
    formattedPaymentAmount
    formattedTotalAmountRefunded
    formattedAmount {
      subtotal
      tax
      discount
      shipping
      total
      totalDiscount
      exchangeRate
    }
    orderHistory {
      id
      status
      title
      body
      icon
      public
      index
      time
    }
  }
}

# {
#   "orderItemId": "61a271d01a6f7e4f081c5263",
#   "requestType": "return", replace
#   "reason": "damaged"
# }
