subscription ($id: ID!) {
  orderUpdated(id: $id) {
    id
    orderNo
    otp
    createdAt
    codPaid
    paymentMode
    paymentAmount
    paymentTxStatus
    paymentReferenceId
    payment {
      amount_paid
      amount_due
    }
    amount {
      qty
      subtotal
      tax
      discount
      total
      shipping
    }
    user {
      firstName
      lastName
      phone
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    items {
      pid
      name
      img
      slug
      price
      qty
      time
      vendor {
        firstName
        lastName
        phone
        address {
          address
        }
        store
      }
      status
    }
  }
}
