mutation updateOrder(
  $id: ID!
  $pid: ID!
  $status: String
  $tracking: String
  $trackingId: String
  $courierName: String
  $returnTrackingId: String
  $returnCourierName: String
) {
  updateOrder(
    id: $id
    pid: $pid
    status: $status
    tracking: $tracking
    trackingId: $trackingId
    courierName: $courierName
    returnTrackingId: $returnTrackingId
    returnCourierName: $returnCourierName
  ) {
    id
    orderNo
    user {
      firstName
      lastName
      phone
    }
    amount {
      qty
      subtotal
      discount
      shipping
      tax
      total
    }
    paymentOrderId
    delivery {
      otp
    }
    items {
      pid
      name
      slug
      img
      price
      qty
      status
      tracking
      vendor {
        firstName
        lastName
        store {
          name
        }
        phone
      }
    }
    address {
      address
      firstName
      lastName
      phone
    }
    createdAt
    updatedAt
  }
}

# {
#   "id": "60eb23fbeee69f0748da49f4",
#   "pid": "60e75ad10c33f8083050cf30",
#   "status": "Shipped",
#   "trackingId": "gdmsams333",
#   "courierName": "DHL",
#   "returnTrackingId": "u989",
# 	"returnCourierName": "gati"
# }
