mutation updateEmailTemplatesData($password: String!, $force: Boolean) {
  updateEmailTemplatesData(password: $password, force: $force)
}

# {
#   "password": "prakash",
#   "force": true
# }
# force:true means ,ignore if s3 or azure delete function not working
