query channelMessages(
  $channel: String!
  $page: Int
  $limit: Int
  $search: String
  $sort: String
) {
  channelMessages(channel: $channel,page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      channel
      message
      firstName
      lastName
      user{
        firstName
        lastName
      }
    }
  }
}


# {
#   "channel": "pra11k"
# }