mutation sendInstantMessage($channel: String!, $message: String) {
  sendInstantMessage(channel: $channel, message: $message) {
    id
    channel
    message
    firstName
    lastName
  }
}


# {
#   "channel":  "11111",
#   "message": "hi"
# }
