mutation saveGlobalOption(
  $id: String!
  $name: String
  $key: String
  $val: String
  $categories: [String]
  $position: Int
  $isFilter: Boolean
  $preselect: Boolean
  $required: Boolean
  $type: String
  $info: String
  $active: Boolean
) {
  saveGlobalOption(
    id: $id
    name: $name
    key: $key
    val: $val
    categories: $categories
    position: $position
    isFilter: $isFilter
    info: $info
    preselect: $preselect
    required: $required
    type: $type
    active: $active
  ) {
    id
    name
    key
    val
    categories
    position
    info
    preselect
    required
    type
    isFilter
    active
    values {
      id
      name
      default
      position
    }
  }
}

# {
#   "id": "new",
#   "name": "color updated",
#   "type": "button"
# }
