query gGetProduct($productId: ID!, $authCode: String!) {
  gGetProduct(productId: $productId, authCode: $authCode) {
    id
    slug
    name
    description
    type
    price
    mrp
    discount
    stock
    tax
    img
    images
    time
    active
    popularity
    position
    ratings
    reviews
    sku
    hsn
    group
    barcode
    gender
    gtin
    condition
    trending
    featured
    hot
    new
    sale
    recommended
    title
    itemId
    warranty
    metaDescription
    keywords
    ageMin
    ageMax
    ageUnit
    styleCode
    eanNo
    articleCode
    productMasterId
    currency
    manufacturer
    countryOfOrigin
    returnInfo
    link
    gender
    condition
    gtin
    cgst
    sgst
    igst
    createdAt
    updatedAt
  }
}
