{{ $deployment := .Values.deployment }}
{{ $hpa := .Values.hpa }}
{{- if $hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $deployment.name }}
spec:
  maxReplicas: {{ $hpa.maxReplicas }}
  minReplicas: {{ $hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deployment.name }}
  targetCPUUtilizationPercentage: {{ $hpa.averageCpuUtilization }}
{{- end }}