query features(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  features(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      value
      type
      product
      active
      store {
        id
        name
        email
      }
    }
  }
}
