query orderStatusOfOrder($order_id: ID!) {
  orderStatusOfOrder(order_id: $order_id) {
    id
    order
    item
    event
    tracking_id
    type
    courier_name
    active
    createdAt
    updatedAt
  }
}

# {
#   "order_id": "6045f1fb0a60784dd0f23ad9"
# }
