mutation saveOrderStatus(
  $id: String!
  $order: ID
  $item: ID
  $event: String
  $tracking_id: String
  $type: String
  $courier_name: String
  $active: Boolean
) {
  saveOrderStatus(
    id: $id
    order: $order
    item: $item
    event: $event
    tracking_id: $tracking_id
    type: $type
    courier_name: $courier_name
    active: $active
  ) {
    id
    order
    item
    event
    tracking_id
    type
    courier_name
    active
    createdAt
    updatedAt
  }
}

# {
#   "id": "new",
#   "order": "60e6f550c4d57b0630d7446c",
#   "item": "60e53dd1f13b3a2f10900217",
#   "event": "Delivered",
#   "courier_name": "DHL",
#   "tracking_id": "12132cddffxcd",
#   "type": "Delivered"
# }
